### ISSUE TITLE
ethercat config question

### ISSUE THREAD

**Issue by tlemsl** [leggedrobotics/maxon_epos_ethercat_sdk#2]
Hi, I'm robotics engineer and working on a project using maxon motor with [epos4](https://www.maxongroup.co.kr/maxon/view/product/control/Positionierung/628092)

It's the first time i use maxon motor and ethercat So,  I'm not good at dealing with ethercat.

I tried example with maxon motor setup and i got these errors
![Screenshot from 2022-02-16 19-34-14](https://user-images.githubusercontent.com/50408036/154247282-29be3316-ab85-4fac-947c-5d135bb9c245.png)

So Should i need to do more configurations for ethercat? and I also wonder meaning about "Excute as root"

Thank you for reading my question and I would appreciate it if you could let me know some document or article what would be good to refer to to to use this .

**Comment by zoenglinghou** [comment]
Linux requires you to be root to interact with your Networking hardware.

You are likely to need to configure the `setup.yaml` to your own hardware setup and your [object dictionaries](https://github.com/leggedrobotics/maxon_epos_ethercat_sdk/blob/master/include/maxon_epos_ethercat_sdk/ObjectDictionary.hpp) to your firmware's specification manual.
